prometheus:
  image: prom/prometheus
  volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  ports:
    - "9091:9090"  # تغيير المنفذ هنا
  networks:
    - monitoring
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'my_app'
    static_configs:
      - targets: ['app:5000']  # تأكد من أن هذا يتناسب مع إعدادات التطبيق الخاص بك
