apiVersion: v1
kind: Service
metadata:
  namespace: Dev
  name: simple-web-app-service
  labels:
    app: web-app
spec:
  type: LoadBalancer  # Expose service through a load balancer
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 80  # External port
    targetPort: 3000  # Port inside the container